_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/lvis/faster_rcnn/faster_rcnn_R_50_FPN_cosine_combined_norepeat/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1230
    OUTPUT_LAYER: "CosineSimOutputLayers"
    SCORE_THRESH_TEST: 0.0001
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("lvis_v0.5_train_shots",)
  TEST: ("lvis_v0.5_val",)
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
# DATALOADER:
#   SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
#   REPEAT_THRESHOLD: 0.001
SOLVER:
  BASE_LR: 0.001
  STEPS: (15000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/lvis/faster_rcnn/faster_rcnn_R_50_FPN_cosine_combined_all_norepeat"